#!/bin/bash
metagen() {
    PYTHONPATH=. ./metagen/main.py "$@"
}

handle_error() {
    ret=$?
    echo FAILED. >&2
    exit ${ret}
}
trap handle_error ERR

unset ECHANGELOG_USER
PS4='# '
set -x
########################################
# BEGIN tests
########################################


#Should fail if ECHANGELOG_USER not set:
ECHANGELOG_USER='First Last <mail@example.org>' metagen -m -Q
! metagen -m -Q

metagen -e "someguy@gentoo.org" -d "Maint desc" -Q

metagen -e "someguy@gentoo.org" -n "Jon Doe" -d "Maint desc" -Q

#Should fail if ECHANGELOG_USER not set:
ECHANGELOG_USER='First Last <mail@example.org>' metagen -m -H python -e "foo@bar.com" -d "Foo bar.","Chow fun" -Q
! metagen -m -H python -e "foo@bar.com" -d "Foo bar.","Chow fun" -Q

#Should fail:
! metagen -Q

#Should fail:
! metagen -l "Long desc" -Q

#Should fail:
! metagen -d "Maintainer desc" -Q


########################################
# END tests
########################################
echo
echo PASSED.
